name: build

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    container: neilotoole/xcgo:latest
    steps:
      - name: sudo
        run: sudo su

      - name: build libs
        run: ./entrypoint.sh
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
