name: build

on:
  push:
  pull_request:

jobs:
  build-libraries:
    runs-on: ubuntu-latest
    container: neilotoole/xcgo:latest
    steps:
      - uses: actions/checkout@v3

      - name: sudo
        run: sudo su

      - name: build libs
        run: ./entrypoint.sh

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux
            build/windows
            build/darwin
